QLThuChiCaNhan/DemoMVC/Controllers/BaoCaoController.cs
using DemoMVC.DangNhap;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DemoMVC.Controllers
{
    public class BaoCaoController : Controller
    {
        private TuTuService service = new TuTuService();
        // GET: BaoCao
        public ActionResult BaoCao()
        {
            return View();
        }


        public ActionResult Report()
        {
            if (Session["User"] != null)
            {
                NguoiDung nd = (NguoiDung)Session["User"];
                int id = nd.mand;
                int thang = DateTime.Now.Month;
                int nam = DateTime.Now.Year;
                int tongchi = service.tinhTongChi(id, thang, nam);
                int tongthu = service.tinhTongThu(id, thang, nam);

                List<TongChiTheoLoai> chitheoloai = service.DSChiTheoLoai(id, thang, nam).ToList();
                List<TongThuTheoLoai> thutheoloai = service.DSThuTheoLoai(id, thang, nam).ToList();

                int k = chitheoloai.Count;
                int h = thutheoloai.Count;

                int i, j;

                string[] loaichi = new string[k];
                int[] tienchi = new int[k];
                string[] loaithu = new string[h];
                int[] tienthu = new int[h];

                for (i = 0; i < k; i++)
                {
                    loaichi[i] = chitheoloai[i].tenloaichi;
                    tienchi[i] = int.Parse(chitheoloai[i].TongChi.ToString());
                }

                for (j = 0; j < h; j++)
                {
                    loaithu[j] = thutheoloai[j].tenloaithu;
                    tienchi[j] = int.Parse(thutheoloai[j].TongThu.ToString());
                }

                ViewBag.chitheoloai = chitheoloai;
                ViewBag.thutheoloai = thutheoloai;

                ViewBag.loaichi = loaichi;
                ViewBag.tienchi = tienchi;
                ViewBag.loaithu = loaithu;
                ViewBag.tienthu = tienthu;
                ViewBag.lengthchi = k;
                ViewBag.lengththu = h;

                ViewBag.tongchi = tongchi;
                ViewBag.tongthu = tongthu;
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
            
        }
    }
}

QLThuChiCaNhan/DemoMVC/Controllers/SoChiTieuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DemoMVC.SoChiTieu;
using DemoMVC.DangNhap;

namespace DemoMVC.Controllers
{
    public class SoChiTieuController : Controller
    {

        private ChiChiService service = new ChiChiService();
        // GET: SoChiTieu
        public ActionResult ChiTieu(string SearchString)
        {
            if (Session["User"] == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var user = (NguoiDung)Session["User"];
            
            DateTime now = DateTime.Now;
            string mathang = now.Year.ToString() + "-" + now.Month.ToString();
            //string mathang = "2020-10";
            List<CTKhoanChiCD> khoanchicd = service.KhoanChiCoDinh(mathang, user.mand).ToList();
            List<CTKhoanChi> khoanchi = service.KhoanChiTheoThang(mathang, user.mand).ToList();
            List<CTKhoanThu> khoanthu = service.KhoanThuTheoThang(mathang, user.mand).ToList();
            List<CTKHoanThuCD> khoanthucd = service.KhoanThuCoDinh(mathang, user.mand).ToList();

            if (!string.IsNullOrEmpty(SearchString))
            {
                 khoanchicd = service.SearchKhoanChiCoDinh(mathang,SearchString, user.mand).ToList();
                 khoanchi = service.SearchKhoanChiTheoThang(mathang, SearchString, user.mand).ToList();
                 khoanthu = service.SearchKhoanThuTheoThang(mathang, SearchString, user.mand).ToList();
                 khoanthucd = service.SearchKhoanThuCoDinh(mathang, user.mand, SearchString).ToList();
            }
            ViewBag.khoanchicd = khoanchicd;
            ViewBag.khoanchi = khoanchi;
            ViewBag.khoanthucd = khoanthucd;
            ViewBag.khoanthu = khoanthu;
            return View();
        }

        public ActionResult AddEditKhoanChiCD(int itemId)
        {
            if (Session["User"] == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var user = (NguoiDung)Session["User"];

            CTKhoanChiCD model = new CTKhoanChiCD();
            if (itemId > 0)
            {
                model = service.kccd(itemId, user.mand);
            }
            ViewBag.khoanchi = model;
            List<LoaiKhoanChi> list = service.LoaiKhoanChi().ToList();
            ViewBag.listkhoanchi = list;
            return PartialView("KhoanChiCDForm");
        }

        [HttpPost]
        public ActionResult Delete(int itemId, int ma)
        {
            if (Session["User"] == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var user = (NguoiDung)Session["User"];
            bool x;
            switch (ma)
            {
                case 0: x = service.XoaKCCD(itemId, user.mand); break;
                case 1: x = service.XoaKTCD(itemId, user.mand); break;
                case 2: x = service.XoaKC(itemId, user.mand); break;
                case 3: x = service.XoaKT(itemId, user.mand); break;
            }

            return RedirectToAction("ChiTieu");
        }

        [HttpPost]
        public ActionResult CreateUpdateKCCD(CTKhoanChiCD kccd)
        {
            if (Session["User"] == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var user = (NguoiDung)Session["User"];
            List<LoaiKhoanChi> list = service.LoaiKhoanChi().ToList();
            int ma = list.Single(s => s.tenloaichi == kccd.tenloaichi).maloaichi;
            kccd.maloaichi = ma;
            kccd.mand = user.mand;
            if (ModelState.IsValid)
            {
                if (kccd.makhoanchi > 0)
                {
                    service.UpdateKCCD(kccd);
                }
                else
                {
                    service.AddKCCD(kccd);
                }
            }
            return RedirectToAction("ChiTieu");
        }
    }
}

QLThuChiCaNhan/DemoMVC/Views/Shared/_Layout.cshtml
@using DemoMVC.DangNhap;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Expense Manager</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        .logo-image {
            border-radius: 50%;
            width: 60px;
            height: 60px;
        }

        .navbar-brand {
            margin-left: 6rem;
        }

        .header ul {
            margin-left: 50px;
        }

            .header ul li {
                margin-left: 30px;
            }

        .profile_details {
            margin-left: 350px;
            margin-right: 6rem;
        }

        .user_image {
            width: 30px;
            height: 30px;
            border-radius: 50%;
        }
    </style>
</head>
@{ 
    var user = (NguoiDung)Session["User"];
}
<body>
    <div class="header">
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark ">
            <!-- Brand/logo -->
            <a class="navbar-brand" href="@Url.Action("ChiTieu", "SoChiTieu")">
                <img class="logo-image" src="/images/Logo.png" alt="Logo">
                <span>ExpanseManager</span>
            </a>
            <!-- Links -->
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="@Url.Action("ChiTieu", "SoChiTieu")">Sổ giao dịch</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Report", "BaoCao")">Báo cáo</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Contact")">Liên hệ</a>
                </li>
                <li class="nav-item dropdown" style="margin-left: 330px; margin-right: 6rem;">
                    @{if (user != null)
                        {
                            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                                <img class="user_image" src="/images/user.png" alt="Hinh ảnh user">
                                @user.tendn.ToString()
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">
                                    <i class="fa fa-user"></i>   Tài khoản
                                </a>
                                <a class="dropdown-item" href="@Url.Action("Logout", "Account")">
                                    <i class="fa fa-sign-out"></i>  Đăng xuất
                                </a>
                            </div>
                        }
                        else
                        {
                            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                                <img class="user_image" src="/images/user.png" alt="Hinh ảnh user">
                                Người dùng
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">
                                    <i class="fa fa-user"></i>   Tài khoản
                                </a>
                                <a class="dropdown-item" href="@Url.Action("Login","Account")">
                                    <i class="fa fa-sign-in"></i>   Đăng nhập
                                </a>
                            </div>
                        }

                    }

                </li>
            </ul>
        </nav>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    <br /><br />
    <div class="footer bg-dark text-white">
        <br />
        <footer style="text-align: center;">
            <p>&copy; @DateTime.Now.Year  - ExpenseManager</p>
        </footer>
        <br />
    </div>
    @*@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>